
function Navbar(){
    return(
        <nav className="navbar">
            <a href="/"className="ApartmentFinder">Apartment Name</a> 
            
                <li>
                    <a href="/home">Home</a>
                    <a href="/about">About</a>
                    <a href="/add Apartment">Add Apartment</a>
                    <a href="/contact">Contact</a>
                </li>
                
        </nav>
    )

}
export default Navbar;
  